from __future__ import annotations

import os
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent
BACKEND_DIR = APP_DIR.parent
PROJECT_DIR = BACKEND_DIR.parent
STATIC_DIR = APP_DIR / "static"
SCENARIOS_DIR = PROJECT_DIR / "scenarios"
DATABASE_PATH = Path(os.getenv("OMIP_DATABASE_PATH", str(BACKEND_DIR / "omip_v052.db")))
STORAGE_DIR = Path(os.getenv("OMIP_STORAGE_DIR", str(BACKEND_DIR / "storage")))
EXPORT_DIR = Path(os.getenv("OMIP_EXPORT_DIR", str(STORAGE_DIR / "exports")))
BACKUP_DIR = Path(os.getenv("OMIP_BACKUP_DIR", str(STORAGE_DIR / "backups")))

MQTT_ENABLED = os.getenv("OMIP_MQTT_ENABLED", "false").strip().lower() in {"1", "true", "yes", "on"}
MQTT_HOST = os.getenv("OMIP_MQTT_HOST", "127.0.0.1")
MQTT_PORT = int(os.getenv("OMIP_MQTT_PORT", "1883"))
MQTT_TOPIC = os.getenv("OMIP_MQTT_TOPIC", "omip/+/sensors/+")
MQTT_TELEMETRY_TOPIC = os.getenv("OMIP_MQTT_TELEMETRY_TOPIC", "omip/+/telemetry")
MQTT_HEARTBEAT_TOPIC = os.getenv("OMIP_MQTT_HEARTBEAT_TOPIC", "omip/+/heartbeat")

ONLINE_THRESHOLD_S = float(os.getenv("OMIP_ONLINE_THRESHOLD_S", "5"))
DEGRADED_THRESHOLD_S = float(os.getenv("OMIP_DEGRADED_THRESHOLD_S", "15"))

# v0.4.1 timing/rate integrity thresholds.
INTEGRITY_RATE_WINDOW_S = float(os.getenv("OMIP_INTEGRITY_RATE_WINDOW_S", "10"))
INTEGRITY_RATE_MIN_SPAN_S = float(os.getenv("OMIP_INTEGRITY_RATE_MIN_SPAN_S", "2"))
INTEGRITY_LOW_RATE_RATIO = float(os.getenv("OMIP_INTEGRITY_LOW_RATE_RATIO", "0.70"))
INTEGRITY_CRITICAL_LOW_RATE_RATIO = float(os.getenv("OMIP_INTEGRITY_CRITICAL_LOW_RATE_RATIO", "0.30"))
INTEGRITY_HIGH_RATE_RATIO = float(os.getenv("OMIP_INTEGRITY_HIGH_RATE_RATIO", "1.30"))
INTEGRITY_WARNING_LATENCY_MS = float(os.getenv("OMIP_INTEGRITY_WARNING_LATENCY_MS", "500"))
INTEGRITY_CRITICAL_LATENCY_MS = float(os.getenv("OMIP_INTEGRITY_CRITICAL_LATENCY_MS", "2000"))
INTEGRITY_FUTURE_WARNING_MS = float(os.getenv("OMIP_INTEGRITY_FUTURE_WARNING_MS", "2000"))
INTEGRITY_FUTURE_CRITICAL_MS = float(os.getenv("OMIP_INTEGRITY_FUTURE_CRITICAL_MS", "10000"))
INTEGRITY_CLOCK_DRIFT_MS = float(os.getenv("OMIP_INTEGRITY_CLOCK_DRIFT_MS", "500"))
INTEGRITY_REALTIME_MAX_SKEW_S = float(os.getenv("OMIP_INTEGRITY_REALTIME_MAX_SKEW_S", "300"))

# v0.4.2 operational monitoring settings.
SYSTEM_SNAPSHOT_INTERVAL_S = float(os.getenv("OMIP_SYSTEM_SNAPSHOT_INTERVAL_S", "10"))
SYSTEM_SNAPSHOT_RETENTION_DAYS = int(os.getenv("OMIP_SYSTEM_SNAPSHOT_RETENTION_DAYS", "7"))
SYSTEM_HEALTH_CHECK_INTERVAL_S = float(os.getenv("OMIP_SYSTEM_HEALTH_CHECK_INTERVAL_S", "5"))
SYSTEM_MEMORY_WARNING_MB = float(os.getenv("OMIP_SYSTEM_MEMORY_WARNING_MB", "1024"))
SYSTEM_INGESTION_REJECTION_WARNING_RATIO = float(os.getenv("OMIP_SYSTEM_INGESTION_REJECTION_WARNING_RATIO", "0.10"))

PUBLIC_API_BASE = os.getenv("OMIP_PUBLIC_API_BASE", "http://127.0.0.1:8000")
